# Generated by Django 5.1.4 on 2024-12-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPv4GeoDataModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ipv4', models.CharField(max_length=15, unique=True)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('province', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('latitude', models.CharField(blank=True, max_length=255)),
                ('longitude', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
