name: Arvan Recruit Challenge - Python Geolocation retrieve API

on:
  push:
    branches: [ "selective-part-1" ]

env:
  USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Build the Docker image and push to docker hub
      run: |
        SHA=$GITHUB_SHA
        IMAGE_TAG=$(echo ${SHA:0:7})
        docker build --file dev.Dockerfile --tag mojecloud/geo_loc_api:$IMAGE_TAG .
        docker login --username $USERNAME --password $PASSWORD
        docker push mojecloud/geo_loc_api:$IMAGE_TAG
  
  post-build:
    runs-on: ubuntu-latest
    needs: build
    env:
      SHA: ${{ github.sha }}
    steps:
    - name: checkout cd repo
      uses: actions/checkout@v4
      with:
        ref: selective-part-1_cd
    - name: Set new built image to cd pipeline
      uses: mikefarah/yq@master
      with:
        cmd: IMG=$(echo ${SHA:0:7}) yq -i '.image.tag = strenv(IMG)' charts/values.yaml
    - name: Push changes to the cd repository
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        IMAGE_TAG=$(echo ${SHA:0:7})
        git commit -m "Push new image 'mojecloud/geo_loc_api:$IMAGE_TAG' to docker registry."
        git push origin selective-part-1_cd
